using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.Nii;
using Content.Shared.Nii.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Nii.UI;

[GenerateTypedNameReferences]
public sealed partial class NiiDirectorTerminalWindow : FancyWindow
{
    public event Action? AuthorizeProjectRequested;

    public NiiDirectorTerminalWindow()
    {
        RobustXamlLoader.Load(this);
        AuthorizeProjectButton.OnPressed += _ => AuthorizeProjectRequested?.Invoke();
    }

    public void UpdateState(NiiDirectorTerminalBuiState state)
    {
        DayValue.Text = state.CurrentDay.ToString();
        BalanceValue.Text = FormatCurrency(state.Balance);
        FundingValue.Text = FormatCurrency(state.DailyFunding);
        ExpensesValue.Text = FormatCurrency(state.DailyExpenses);
        DailyResultValue.Text = FormatCurrency(state.DailyFunding - state.DailyExpenses);
        ReputationValue.Text = state.Reputation.ToString();
        ScienceValue.Text = state.Science.ToString();
        BankruptcyPanel.Visible = state.IsBankrupt;
        ProjectNameValue.Text = state.ProjectName;
        ProjectStatusValue.Text = Loc.GetString(StatusLocId(state.ResearchStatus));
        ProjectCostValue.Text = FormatCurrency(state.ProjectCost);
        ProjectReagentValue.Text = Loc.GetString(
            "nii-terminal-project-reagent-value",
            ("amount", state.RequiredReagentAmount));
        ProjectDurationValue.Text = Loc.GetString(
            "nii-terminal-project-duration-value",
            ("seconds", state.ProjectDurationSeconds));
        AuthorizeProjectButton.Disabled = !state.CanAuthorize;
        WorkOrderStatusValue.Text = state.HasWorkOrder
            ? Loc.GetString(WorkOrderStatusLocId(state.WorkOrderStatus))
            : Loc.GetString("nii-work-order-status-none");
        WorkOrderAssigneeValue.Text = string.IsNullOrEmpty(state.AssignedEmployeeName)
            ? Loc.GetString("nii-work-order-assignee-none")
            : state.AssignedEmployeeName;
        var isBlocked = state.HasWorkOrder && state.WorkOrderStatus == NiiWorkOrderStatus.Blocked;
        WorkOrderBlockLabel.Visible = isBlocked;
        WorkOrderBlockValue.Visible = isBlocked;
        WorkOrderBlockValue.Text = isBlocked
            ? Loc.GetString(WorkOrderBlockReasonLocId(state.WorkOrderBlockReason))
            : string.Empty;
        EventLogValue.Text = string.Join("\n", state.EventLog.Select(EventText));
    }

    private static string FormatCurrency(int amount)
    {
        return Loc.GetString("nii-terminal-currency", ("amount", amount));
    }

    private static string StatusLocId(NiiResearchStatus status)
    {
        return status switch
        {
            NiiResearchStatus.Available => "nii-research-status-available",
            NiiResearchStatus.Authorized => "nii-research-status-authorized",
            NiiResearchStatus.Running => "nii-research-status-running",
            NiiResearchStatus.Completed => "nii-research-status-completed",
            _ => "nii-research-status-available",
        };
    }

    private static string EventText(NiiInstituteEventType eventType)
    {
        var locId = eventType switch
        {
            NiiInstituteEventType.InstituteStarted => "nii-event-institute-started",
            NiiInstituteEventType.ProjectAuthorized => "nii-event-project-authorized",
            NiiInstituteEventType.ResearchStarted => "nii-event-research-started",
            NiiInstituteEventType.ResearchCompleted => "nii-event-research-completed",
            _ => "nii-event-institute-started",
        };

        return $"- {Loc.GetString(locId)}";
    }

    private static string WorkOrderStatusLocId(NiiWorkOrderStatus status)
    {
        return status switch
        {
            NiiWorkOrderStatus.Created => "nii-work-order-status-created",
            NiiWorkOrderStatus.AwaitingAssignment => "nii-work-order-status-awaiting-assignment",
            NiiWorkOrderStatus.Assigned => "nii-work-order-status-assigned",
            NiiWorkOrderStatus.FetchingSample => "nii-work-order-status-fetching-sample",
            NiiWorkOrderStatus.DeliveringSample => "nii-work-order-status-delivering-sample",
            NiiWorkOrderStatus.Running => "nii-work-order-status-running",
            NiiWorkOrderStatus.Completed => "nii-work-order-status-completed",
            NiiWorkOrderStatus.Blocked => "nii-work-order-status-blocked",
            NiiWorkOrderStatus.Cancelled => "nii-work-order-status-cancelled",
            _ => "nii-work-order-status-none",
        };
    }

    private static string WorkOrderBlockReasonLocId(NiiWorkOrderBlockReason reason)
    {
        return reason switch
        {
            NiiWorkOrderBlockReason.NoSample => "nii-work-order-block-no-sample",
            NiiWorkOrderBlockReason.SampleInaccessible => "nii-work-order-block-sample-inaccessible",
            NiiWorkOrderBlockReason.MachineBusy => "nii-work-order-block-machine-busy",
            NiiWorkOrderBlockReason.MachineInaccessible => "nii-work-order-block-machine-inaccessible",
            NiiWorkOrderBlockReason.EmployeeUnavailable => "nii-work-order-block-employee-unavailable",
            _ => "nii-work-order-block-none",
        };
    }
}
