using Content.Client.UserInterface.Controls;
using Content.Shared.Nii.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Nii.UI;

[GenerateTypedNameReferences]
public sealed partial class NiiDirectorTerminalWindow : FancyWindow
{
    public NiiDirectorTerminalWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(NiiDirectorTerminalBuiState state)
    {
        DayValue.Text = state.CurrentDay.ToString();
        BalanceValue.Text = FormatCurrency(state.Balance);
        FundingValue.Text = FormatCurrency(state.DailyFunding);
        ExpensesValue.Text = FormatCurrency(state.DailyExpenses);
        DailyResultValue.Text = FormatCurrency(state.DailyFunding - state.DailyExpenses);
        ReputationValue.Text = state.Reputation.ToString();
        ScienceValue.Text = state.Science.ToString();
        BankruptcyPanel.Visible = state.IsBankrupt;
    }

    private static string FormatCurrency(int amount)
    {
        return Loc.GetString("nii-terminal-currency", ("amount", amount));
    }
}
