using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.Nii;
using Content.Shared.Nii.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Nii.UI;

[GenerateTypedNameReferences]
public sealed partial class NiiDirectorTerminalWindow : FancyWindow
{
    public event Action? AuthorizeProjectRequested;
    public event Action<NetEntity>? AssignResearcherRequested;
    public event Action<bool>? DelegatedAssignmentRequested;

    private NiiDirectorTerminalBuiState? _state;
    private NiiEmployeeUiState[] _researchers = [];

    public NiiDirectorTerminalWindow()
    {
        RobustXamlLoader.Load(this);
        AuthorizeProjectButton.OnPressed += _ => AuthorizeProjectRequested?.Invoke();
        AssignResearcherButton.OnPressed += _ => RequestAssignment();
        ToggleDelegationButton.OnPressed += _ => DelegatedAssignmentRequested?.Invoke(
            _state?.AssignmentMode != NiiLaboratoryAssignmentMode.Delegated);
        ResearcherSelector.OnItemSelected += args =>
        {
            args.Button.SelectId(args.Id);
            UpdateAssignmentControls();
        };
    }

    public void UpdateState(NiiDirectorTerminalBuiState state)
    {
        _state = state;
        DayValue.Text = state.CurrentDay.ToString();
        BalanceValue.Text = FormatCurrency(state.Balance);
        FundingValue.Text = FormatCurrency(state.DailyFunding);
        ExpensesValue.Text = FormatCurrency(state.DailyExpenses);
        DailyResultValue.Text = FormatCurrency(state.DailyFunding - state.DailyExpenses);
        ReputationValue.Text = state.Reputation.ToString();
        ScienceValue.Text = state.Science.ToString();
        BankruptcyPanel.Visible = state.IsBankrupt;
        ProjectNameValue.Text = state.ProjectName;
        ProjectStatusValue.Text = Loc.GetString(StatusLocId(state.ResearchStatus));
        ProjectCostValue.Text = FormatCurrency(state.ProjectCost);
        ProjectReagentValue.Text = Loc.GetString(
            "nii-terminal-project-reagent-value",
            ("amount", state.RequiredReagentAmount));
        ProjectDurationValue.Text = Loc.GetString(
            "nii-terminal-project-duration-value",
            ("seconds", state.ProjectDurationSeconds));
        AuthorizeProjectButton.Disabled = !state.CanAuthorize;
        WorkOrderStatusValue.Text = state.HasWorkOrder
            ? Loc.GetString(WorkOrderStatusLocId(state.WorkOrderStatus))
            : Loc.GetString("nii-work-order-status-none");
        WorkOrderAssigneeValue.Text = string.IsNullOrEmpty(state.AssignedEmployeeName)
            ? Loc.GetString("nii-work-order-assignee-none")
            : state.AssignedEmployeeName;
        var isBlocked = state.HasWorkOrder && state.WorkOrderStatus == NiiWorkOrderStatus.Blocked;
        WorkOrderBlockLabel.Visible = isBlocked;
        WorkOrderBlockValue.Visible = isBlocked;
        WorkOrderBlockValue.Text = isBlocked
            ? Loc.GetString(WorkOrderBlockReasonLocId(state.WorkOrderBlockReason))
            : string.Empty;
        UpdateLaboratory(state);
        EventLogValue.Text = string.Join("\n", state.EventLog.Select(EventText));
    }

    private void UpdateLaboratory(NiiDirectorTerminalBuiState state)
    {
        LaboratoryPanel.Visible = state.HasLaboratory;
        if (!state.HasLaboratory)
            return;

        LaboratoryHeadValue.Text = string.IsNullOrEmpty(state.LaboratoryHeadName)
            ? Loc.GetString("nii-terminal-employee-none")
            : state.LaboratoryHeadName;
        LaboratoryHeadStatusValue.Text = Loc.GetString(EmployeeAvailabilityLocId(state.LaboratoryHeadAvailability));
        AssignmentModeValue.Text = Loc.GetString(state.AssignmentMode == NiiLaboratoryAssignmentMode.Delegated
            ? "nii-assignment-mode-delegated"
            : "nii-assignment-mode-manual");
        ToggleDelegationButton.Text = Loc.GetString(state.AssignmentMode == NiiLaboratoryAssignmentMode.Delegated
            ? "nii-terminal-delegation-disable"
            : "nii-terminal-delegation-enable");
        ToggleDelegationButton.Disabled = state.AssignmentMode == NiiLaboratoryAssignmentMode.Manual &&
                                          state.LaboratoryHeadAvailability != NiiEmployeeAvailability.Available;

        var selectedEntity = ResearcherSelector.ItemCount > 0 &&
                             ResearcherSelector.SelectedId >= 0 &&
                             ResearcherSelector.SelectedId < _researchers.Length
            ? _researchers[ResearcherSelector.SelectedId].Entity
            : NetEntity.Invalid;
        _researchers = state.Researchers;
        ResearcherSelector.Clear();
        for (var i = 0; i < _researchers.Length; i++)
        {
            var researcher = _researchers[i];
            ResearcherSelector.AddItem(Loc.GetString(
                "nii-terminal-researcher-option",
                ("name", researcher.Name),
                ("status", Loc.GetString(EmployeeAvailabilityLocId(researcher.Availability)))), i);
        }

        var selectedIndex = Array.FindIndex(_researchers, researcher => researcher.Entity == selectedEntity);
        if (selectedIndex >= 0)
            ResearcherSelector.TrySelectId(selectedIndex);

        ResearcherSelector.Disabled = _researchers.Length == 0;
        UpdateAssignmentControls();
    }

    private void UpdateAssignmentControls()
    {
        if (_state is null)
            return;

        var hasSelection = ResearcherSelector.ItemCount > 0 &&
                           ResearcherSelector.SelectedId >= 0 &&
                           ResearcherSelector.SelectedId < _researchers.Length;
        var selectedAvailable = hasSelection &&
                                _researchers[ResearcherSelector.SelectedId].Availability ==
                                NiiEmployeeAvailability.Available;
        var awaitingAssignment = _state.HasWorkOrder &&
                                 _state.WorkOrderStatus == NiiWorkOrderStatus.AwaitingAssignment;
        AssignResearcherButton.Disabled = !awaitingAssignment || !selectedAvailable;

        AssignmentHintValue.Text = AssignmentHint(_state, awaitingAssignment);
    }

    private string AssignmentHint(NiiDirectorTerminalBuiState state, bool awaitingAssignment)
    {
        if (state.Researchers.Length == 0)
            return Loc.GetString("nii-terminal-assignment-no-researchers");
        if (!awaitingAssignment)
            return Loc.GetString("nii-terminal-assignment-no-pending-order");
        if (state.Researchers.All(employee => employee.Availability != NiiEmployeeAvailability.Available))
            return Loc.GetString("nii-terminal-assignment-no-available-researchers");
        if (state.AssignmentMode == NiiLaboratoryAssignmentMode.Delegated)
            return Loc.GetString("nii-terminal-assignment-delegated");
        return Loc.GetString("nii-terminal-assignment-manual");
    }

    private void RequestAssignment()
    {
        if (ResearcherSelector.ItemCount == 0 ||
            ResearcherSelector.SelectedId < 0 ||
            ResearcherSelector.SelectedId >= _researchers.Length)
            return;

        AssignResearcherRequested?.Invoke(_researchers[ResearcherSelector.SelectedId].Entity);
    }

    private static string FormatCurrency(int amount)
    {
        return Loc.GetString("nii-terminal-currency", ("amount", amount));
    }

    private static string StatusLocId(NiiResearchStatus status)
    {
        return status switch
        {
            NiiResearchStatus.Available => "nii-research-status-available",
            NiiResearchStatus.Authorized => "nii-research-status-authorized",
            NiiResearchStatus.Running => "nii-research-status-running",
            NiiResearchStatus.Completed => "nii-research-status-completed",
            _ => "nii-research-status-available",
        };
    }

    private static string EventText(NiiInstituteEventType eventType)
    {
        var locId = eventType switch
        {
            NiiInstituteEventType.InstituteStarted => "nii-event-institute-started",
            NiiInstituteEventType.ProjectAuthorized => "nii-event-project-authorized",
            NiiInstituteEventType.ResearchStarted => "nii-event-research-started",
            NiiInstituteEventType.ResearchCompleted => "nii-event-research-completed",
            _ => "nii-event-institute-started",
        };

        return $"- {Loc.GetString(locId)}";
    }

    private static string WorkOrderStatusLocId(NiiWorkOrderStatus status)
    {
        return status switch
        {
            NiiWorkOrderStatus.Created => "nii-work-order-status-created",
            NiiWorkOrderStatus.AwaitingAssignment => "nii-work-order-status-awaiting-assignment",
            NiiWorkOrderStatus.Assigned => "nii-work-order-status-assigned",
            NiiWorkOrderStatus.FetchingSample => "nii-work-order-status-fetching-sample",
            NiiWorkOrderStatus.DeliveringSample => "nii-work-order-status-delivering-sample",
            NiiWorkOrderStatus.Running => "nii-work-order-status-running",
            NiiWorkOrderStatus.Completed => "nii-work-order-status-completed",
            NiiWorkOrderStatus.Blocked => "nii-work-order-status-blocked",
            NiiWorkOrderStatus.Cancelled => "nii-work-order-status-cancelled",
            _ => "nii-work-order-status-none",
        };
    }

    private static string WorkOrderBlockReasonLocId(NiiWorkOrderBlockReason reason)
    {
        return reason switch
        {
            NiiWorkOrderBlockReason.NoSample => "nii-work-order-block-no-sample",
            NiiWorkOrderBlockReason.SampleInaccessible => "nii-work-order-block-sample-inaccessible",
            NiiWorkOrderBlockReason.MachineBusy => "nii-work-order-block-machine-busy",
            NiiWorkOrderBlockReason.MachineInaccessible => "nii-work-order-block-machine-inaccessible",
            NiiWorkOrderBlockReason.EmployeeUnavailable => "nii-work-order-block-employee-unavailable",
            _ => "nii-work-order-block-none",
        };
    }

    private static string EmployeeAvailabilityLocId(NiiEmployeeAvailability availability)
    {
        return availability switch
        {
            NiiEmployeeAvailability.Available => "nii-employee-availability-available",
            NiiEmployeeAvailability.Busy => "nii-employee-availability-busy",
            NiiEmployeeAvailability.Unavailable => "nii-employee-availability-unavailable",
            _ => "nii-employee-availability-unavailable",
        };
    }
}
